[supervisord]
nodaemon=true
user=appuser

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
user=appuser

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
user=appuser